site_name: BlazorWebFormsComponents
site_description: A collection of Blazor components that emulate the web forms components of the same name
site_author: Jeffrey T. Fritz
site_url: https://fritzandfriends.github.io/BlazorWebFormsComponents/
edit_uri: edit/dev/docs/
docs_dir: docs

repo_name: FritzAndFriends/BlazorWebFormsComponents
repo_url: https://github.com/FritzAndFriends/BlazorWebFormsComponents

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FritzAndFriends/BlazorWebFormsComponents

theme:
    name: material
    language: en
    palette:
      scheme: default
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    logo: assets/logo.png
    favicon: assets/favicon.ico

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - footnotes
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - exclude:
      glob:
        - "_overrides/*"
        - "Dockerfile"
  - git-revision-date-localized:
      type: iso_datetime
  - macros
  - search:
      lang:
        - en

nav:
  - Home: README.md
  - Editor Controls:
    - AdRotator: EditorControls/AdRotator.md
    - BulletedList: EditorControls/BulletedList.md
    - Button: EditorControls/Button.md
    - CheckBox: EditorControls/CheckBox.md
    - CheckBoxList: EditorControls/CheckBoxList.md
    - DropDownList: EditorControls/DropDownList.md
    - FileUpload: EditorControls/FileUpload.md
    - HiddenField: EditorControls/HiddenField.md
    - Image: EditorControls/Image.md
    - ImageButton: EditorControls/ImageButton.md
    - Label: EditorControls/Label.md
    - LinkButton: EditorControls/LinkButton.md
    - ListBox: EditorControls/ListBox.md
    - Literal: EditorControls/Literal.md
    - Panel: EditorControls/Panel.md
    - PlaceHolder: EditorControls/PlaceHolder.md
    - RadioButton: EditorControls/RadioButton.md
    - RadioButtonList: EditorControls/RadioButtonList.md
    - Table: EditorControls/Table.md
    - TextBox: EditorControls/TextBox.md
  - Data Controls:
    - DataGrid: DataControls/DataGrid.md
    - DataList: DataControls/DataList.md
    - DataPager: DataControls/DataPager.md
    - FormView: DataControls/FormView.md
    - GridView: DataControls/GridView.md
    - ListView: DataControls/ListView.md
    - Repeater: DataControls/Repeater.md
  - Validation Controls:
    - CompareValidator: ValidationControls/CompareValidator.md
    - CustomValidator: ValidationControls/CustomValidator.md
    - RangeValidator: ValidationControls/RangeValidator.md
    - RegularExpressionValidator: ValidationControls/RegularExpressionValidator.md
    - RequiredFieldValidator: ValidationControls/RequiredFieldValidator.md
    - ValidationSummary: ValidationControls/ValidationSummary.md
  - Navigation Controls:
    - HyperLink: NavigationControls/HyperLink.md
    - Menu: NavigationControls/Menu.md
    - SiteMapPath: NavigationControls/SiteMapPath.md
    - TreeView: NavigationControls/TreeView.md
  - Login Controls:
    - Login: LoginControls/Login.md
    - LoginName: LoginControls/LoginName.md
    - LoginStatus: LoginControls/LoginStatus.md
    - LoginView: LoginControls/LoginView.md
  - Utility Features:
    - Databinder: UtilityFeatures/Databinder.md
    - ID Rendering: UtilityFeatures/IDRendering.md
    - JavaScript Setup: UtilityFeatures/JavaScriptSetup.md
    - ViewState: UtilityFeatures/ViewState.md
  - Migration:
      - Getting started: Migration/readme.md
      - Migration Strategies: Migration/Strategies.md
      - Custom Controls: Migration/Custom-Controls.md
      - Master Pages: Migration/MasterPages.md
      - .NET Standard to the Rescue: Migration/NET-Standard.md
      - User Controls: Migration/User-Controls.md
      - Web Forms Application Migration Readiness: Migration/migration_readiness.md
